services:
  db:
    image: postgres
    restart: on-failure
    volumes:
      - wav_converter:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
  wav_converter:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: on-failure
    container_name: wav_converter
    depends_on:
      - db


volumes:
  wav_converter: