services:
  db:
    image: postgres
    restart: on-failure
    volumes:
      - wav_converter:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env

volumes:
  wav_converter: